from django.db import models
from statement.models import Statement
from django.contrib import admin
from django.db import connection


class ReturnAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Return(models.Model):
    class Status(models.TextChoices):
        SUCCESS = "Success"
        FAILED = "Failed"
        PENDING = "Pending"

    return_id = models.CharField(primary_key=True, max_length=255)
    statement = models.ForeignKey(Statement, models.CASCADE, blank=True, null=True)
    delivery_note = models.ForeignKey(
        "delivery.DeliveryNote", models.DO_NOTHING, blank=True, null=True
    )
    return_date = models.DateTimeField(blank=True, null=True)
    status = models.TextField(
        choices=Status, default=Status.PENDING
    )  # This field type is a guess.
    remarks = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"sales"."return"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.return_id:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            self.update()
        else:
            self.insert()

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO sales.return (statement_id, delivery_note_id, return_date, status, remarks)
                VALUES (%s, %s, %s, %s)
                RETURNING quotation_id;
            """,
                [
                    self.statement.statement_id,
                    self.delivery_note.delivery_note_id,
                    self.return_date,
                    self.status,
                    self.remarks,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.return_id = row[0]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.return 
                SET statement_id = %s, delivery_note_id = %s, return_date = %s, status = %s, remarks = %s
                WHERE return_id = %s;
            """,
                [
                    self.statement.statement_id,
                    self.delivery_note.delivery_note_id,
                    self.return_date,
                    self.status,
                    self.remarks,
                    self.return_id,
                ],
            )


class CreditMemo(models.Model):
    credit_memo_id = models.CharField(primary_key=True, max_length=255)
    created_at = models.DateTimeField(blank=True, null=True)
    due_date = models.DateField(blank=True, null=True)
    total_amount = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )

    class Meta:
        managed = False
        db_table = '"sales"."credit_memo"'
