# Generated by Django 5.1.6 on 2025-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
