# Generated by Django 5.1.6 on 2025-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_alter_quotation_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
