# Generated by Django 5.1.6 on 2025-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('email_address', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.TextField(max_length=255)),
                ('address_line2', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('customer_type', models.TextField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Client', 'Client')])),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')])),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
