# Generated by Django 5.1.6 on 2025-03-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('misc', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.generalledgeraccounts'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.businesspartnermaster'),
        ),
    ]
