# Generated by Django 5.1.6 on 2025-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_gl_account_alter_customer_partner_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='"sales"."customers"',
        ),
    ]
