from django.db import models
from datetime import datetime
from misc.human_resources.models import Employees
from misc.admin.models import BusinessPartnerMaster
from django.utils import timezone
from customer.models import Customer
from django.contrib import admin
from django.db import connection


class CampaignsAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Campaigns(models.Model):
    class Type(models.TextChoices):
        EMAIL = "Email"
        SMS = "SMS"
        REFERRAL = "Referral"

    campaign_id = models.CharField(primary_key=True, max_length=255, blank=True)
    campaign_name = models.CharField(max_length=255)
    type = models.TextField(choices=Type, default=Type.EMAIL)
    start_date = models.DateTimeField(default=timezone.now())
    end_date = models.DateTimeField(default=timezone.now())

    class Meta:
        managed = False
        db_table = '"sales"."campaigns"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.campaign_id:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            self.update()
        else:
            self.insert()

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO sales.campaigns (campaign_name, type, start_date, end_date)
                VALUES (%s, %s, %s, %s)
                RETURNING campaign_id;
            """,
                [
                    self.campaign_name,
                    self.type,
                    self.start_date,
                    self.end_date,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.campaign_id = row[
                    0
                ]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.campaigns 
                SET campaign_name = %s, type = %s, start_date = %s, end_date = %s
                WHERE campaign_id = %s;
            """,
                [
                    self.campaign_name,
                    self.type,
                    self.start_date,
                    self.end_date,
                    self.campaign_id,
                ],
            )


class CampaignStatusView(models.Model):
    campaign_id = models.CharField(primary_key=True, max_length=255)
    campaign_name = models.CharField(max_length=255)
    type = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    status = models.CharField(max_length=20)  # Computed field from the view

    class Meta:
        managed = False
        db_table = (
            '"sales"."campaign_status_view"'  # Use the name of the PostgreSQL view
        )


class CampaignContacts(models.Model):
    class ResponseStatus(models.TextChoices):
        INTERESTED = "Interested"
        NOT_INTERESTED = "Not Interested"
        PENDING = "Pending"

    contact_id = models.CharField(primary_key=True, max_length=255, blank=True)
    customer = models.ForeignKey(
        to=Customer, on_delete=models.CASCADE, related_name="campaigns"
    )
    campaign = models.ForeignKey(
        to=Campaigns, on_delete=models.CASCADE, related_name="contacts"
    )
    response_status = models.TextField(
        choices=ResponseStatus, default=ResponseStatus.PENDING
    )

    class Meta:
        managed = False
        db_table = '"sales"."campaign_contacts"'


class Opportunities(models.Model):
    class Stage(models.TextChoices):
        PROSPECTING = "Prospecting"
        NEGOTIATION = "Negotiation"
        CLOSED = "Closed"

    class Status(models.TextChoices):
        OPEN = "Open"
        WON = "Won"
        LOST = "Lost"

    class InterestLevel(models.TextChoices):
        LOW = "Low"
        MEDIUM = "Medium"
        HIGH = "High"
        VERY_HIGH = "Very High"

    opportunity_id = models.CharField(primary_key=True, max_length=255, blank=True)
    customer = models.ForeignKey(
        to="customer.Customer", on_delete=models.SET_NULL, null=True
    )
    partner = models.ForeignKey(
        to=BusinessPartnerMaster, on_delete=models.SET_NULL, null=True
    )
    salesrep = models.ForeignKey(to=Employees, on_delete=models.SET_NULL, null=True)
    estimated_value = models.DecimalField(max_digits=10, decimal_places=2)
    weighted_amount = models.DecimalField(max_digits=10, decimal_places=2)
    gross_profit_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    gross_profit_total = models.DecimalField(max_digits=10, decimal_places=2)
    starting_date = models.DateTimeField()
    expected_closed_date = models.DateField(default=timezone.now())
    stage = models.TextField(choices=Stage)
    status = models.TextField(choices=Status)
    description = models.TextField(blank=True, null=True)
    reason_lost = models.TextField(blank=True, null=True)
    interest_level = models.TextField(choices=InterestLevel)

    class Meta:
        managed = False
        db_table = '"sales"."opportunities"'


class TicketAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Ticket(models.Model):
    class Status(models.TextChoices):
        OPEN = "Open"
        IN_PROGRESS = "In Progress"
        CLOSED = "Closed"

    class Priority(models.TextChoices):
        LOW = "Low"
        MEDIUM = "Medium"
        HIGH = "High"
        URGENT = "Urgent"

    class Type(models.TextChoices):
        SALES = "Sales"
        SERVICE = "Service"

    ticket_id = models.CharField(primary_key=True, max_length=255, blank=True)
    customer = models.ForeignKey(to="customer.Customer", on_delete=models.CASCADE)
    salesrep = models.ForeignKey(to=Employees, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length=255)
    description = models.TextField()
    type = models.TextField(choices=Type)
    status = models.TextField(choices=Status)
    priority = models.TextField(choices=Priority)
    created_at = models.DateTimeField(default=timezone.now())

    class Meta:
        managed = False
        db_table = '"sales"."ticket"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.ticket_id:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            self.update()
        else:
            self.insert()

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO sales.ticket (customer_id, salesrep_id, subject, description, status, priority, created_at, type)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING ticket_id;
            """,
                [
                    self.customer.customer_id,
                    self.salesrep.employee_id,
                    self.subject,
                    self.description,
                    self.status,
                    self.priority,
                    self.created_at,
                    self.type,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.ticket_id = row[0]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.ticket 
                SET customer_id = %s, salesrep_id = %s, subject = %s, description = %s, status = %s, priority = %s, created_at = %s, type = %s
                WHERE ticket_id = %s;
            """,
                [
                    self.customer.customer_id,
                    self.salesrep.employee_id,
                    self.subject,
                    self.description,
                    self.status,
                    self.priority,
                    self.created_at,
                    self.type,
                    self.ticket_id,
                ],
            )


class TicketConvo(models.Model):
    convo_id = models.CharField(primary_key=True, max_length=255, blank=True)
    ticket = models.ForeignKey(
        to=Ticket, on_delete=models.CASCADE, related_name="conversations"
    )
    subject = models.CharField(max_length=255)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now())

    class Meta:
        managed = False
        db_table = '"sales"."ticket_convo"'
