# Generated by Django 5.1.6 on 2025-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': '"admin"."assets"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceTracking',
            fields=[
                ('attendance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."attendance_tracking"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suspicious_activity', models.BooleanField(blank=True, null=True)),
                ('security_measures', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."audit_log"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillingReceipt',
            fields=[
                ('billing_receipt_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_receipt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_billing_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"distribution"."billing_receipt"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('bom_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_notes', models.TextField(blank=True, null=True)),
                ('quantity_of_unit', models.IntegerField(blank=True, null=True)),
                ('cost_per_raw_material', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost_of_raw_materials', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"mrp"."bill_of_materials"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPartnerMaster',
            fields=[
                ('partner_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('category', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"admin"."business_partner_master"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=20)),
                ('contract_duration', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."candidates"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('carrier_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('carrier_name', models.TextField()),
                ('service_type', models.TextField(blank=True, null=True)),
                ('carrier_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"distribution"."carrier"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'accounting.chart_of_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractualWorkerRequest',
            fields=[
                ('request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_id', models.CharField(max_length=255)),
                ('dept_id', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('required_position', models.CharField(max_length=50)),
                ('employment_type', models.TextField()),
            ],
            options={
                'db_table': '"project_management"."contractual_worker_request"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': '"accounting"."currency"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_project_based', models.TextField(blank=True, null=True)),
                ('is_partial_delivery', models.TextField(blank=True, null=True)),
                ('service_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('production_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_request_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"distribution"."delivery_order"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('delivery_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('received_by', models.IntegerField()),
                ('signature', models.TextField()),
                ('receipt_status', models.TextField(blank=True, null=True)),
                ('shipment_id', models.IntegerField()),
            ],
            options={
                'db_table': '"distribution"."delivery_receipt"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': '"human_resources"."departments"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('performance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('immediate_superior_id', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."employee_performance"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."employees"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('salary_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_pay_type', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_contract_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField()),
            ],
            options={
                'db_table': '"human_resources"."employee_salary"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectCostManagement',
            fields=[
                ('project_resources_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255)),
                ('cost_id', models.CharField(max_length=255)),
                ('project_budget_approval', models.TextField()),
            ],
            options={
                'db_table': '"project_management"."external_project_cost_management"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_request_id', models.CharField(max_length=255)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': '"project_management"."external_project_details"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"project_management"."external_project_labor"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(max_length=50)),
                ('ext_project_description', models.TextField(blank=True, null=True)),
                ('approval_id', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"project_management"."external_project_request"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTaskList',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.TextField()),
                ('task_deadline', models.DateField()),
                ('employee_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"project_management"."external_project_task_list"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTracking',
            fields=[
                ('project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255)),
                ('project_milestone', models.TextField()),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('project_warranty_id', models.CharField(max_length=255)),
                ('project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"project_management"."external_project_tracking"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectWarranty',
            fields=[
                ('project_warranty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=255)),
                ('warranty_coverage_yr', models.IntegerField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
            ],
            options={
                'db_table': '"project_management"."external_project_warranty"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedShipment',
            fields=[
                ('failed_shipment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('failure_date', models.DateField(blank=True, null=True)),
                ('failure_reason', models.TextField()),
                ('resolution_status', models.TextField(blank=True, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"distribution"."failed_shipment"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccounts',
            fields=[
                ('gl_account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_code', models.IntegerField()),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"accounting"."general_ledger_accounts"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('goods_issue_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.IntegerField()),
                ('billing_receipt_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"distribution"."goods_issue"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_request_id', models.CharField(max_length=255)),
                ('intrnl_project_status', models.TextField()),
            ],
            options={
                'db_table': '"project_management"."internal_project_details"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectLabor',
            fields=[
                ('intrnl_project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"project_management"."internal_project_labor"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('request_valid_date', models.DateField()),
                ('request_starting_date', models.DateField()),
                ('approval_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('dept_id', models.CharField(max_length=255)),
                ('project_type', models.TextField()),
            ],
            options={
                'db_table': '"project_management"."internal_project_request"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTaskList',
            fields=[
                ('intrnl_task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_id', models.CharField(max_length=255)),
                ('intrnl_task_description', models.TextField(blank=True, null=True)),
                ('intrnl_task_status', models.TextField()),
                ('intrnl_task_deadline', models.DateField()),
                ('employee_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"project_management"."internal_project_task_list"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTracking',
            fields=[
                ('intrnl_project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_id', models.CharField(max_length=255)),
                ('intrnl_start_date', models.DateField()),
                ('intrnl_estimated_end_date', models.DateField()),
                ('intrnl_project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"project_management"."internal_project_tracking"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('interview_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(max_length=255)),
                ('interviewer_id', models.CharField(max_length=255)),
                ('interview_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."interviews"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."item_master_data"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_id', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('employment_type', models.CharField(max_length=20)),
                ('contract_duration', models.SmallIntegerField(blank=True, null=True)),
                ('contract_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_pay_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."job_posting"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('journal_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('journal_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"accounting"."journal_entries"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLines',
            fields=[
                ('entry_line_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gl_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_id', models.CharField(max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"accounting"."journal_entry_lines"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('leave_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('dept_id', models.CharField(max_length=255)),
                ('immediate_superior_id', models.CharField(max_length=255)),
                ('management_approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."leave_requests"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticsApprovalRequest',
            fields=[
                ('approval_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=255)),
                ('delivery_order_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"distribution"."logistics_approval_request"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonProjectOrderPricing',
            fields=[
                ('non_project_costing_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('mrp_base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"mrp"."non_project_order_pricing"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('operational_cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('additional_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_operational_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_cost_id', models.CharField(blank=True, max_length=255, null=True)),
                ('packing_cost_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"distribution"."operational_cost"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverallProduction',
            fields=[
                ('cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bom_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_of_raw_materials', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_of_production', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_mrp_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"mrp"."overall_production"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackingCost',
            fields=[
                ('packing_cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_packing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"distribution"."packing_cost"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('packing_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('packed_by', models.CharField(max_length=255)),
                ('packing_status', models.TextField(blank=True, null=True)),
                ('packing_type', models.TextField(blank=True, null=True)),
                ('total_items_packed', models.IntegerField(blank=True, null=True)),
                ('packing_cost_id', models.CharField(blank=True, max_length=255, null=True)),
                ('picking_list_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"distribution"."packing_list"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=20)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_days', models.IntegerField(blank=True, null=True)),
                ('contract_pay_type', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_contract_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': '"human_resources"."payroll"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('picking_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('picked_by', models.CharField(max_length=255)),
                ('picked_status', models.TextField(blank=True, null=True)),
                ('picked_date', models.DateField(blank=True, null=True)),
                ('approval_request_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"distribution"."picking_list"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."policies"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalItems',
            fields=[
                ('principal_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"mrp"."principal_items"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_level', models.IntegerField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('policy_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"admin"."products"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': '"admin"."raw_materials"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('rejection_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rejection_status', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField()),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('delivery_receipt_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"distribution"."rejection"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReworkOrder',
            fields=[
                ('rework_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('assigned_to', models.CharField(max_length=255)),
                ('rework_status', models.TextField(blank=True, null=True)),
                ('rework_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateTimeField(blank=True, null=True)),
                ('rejection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_shipment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"distribution"."rework_order"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesPermission',
            fields=[
                ('role_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('access_level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."roles_permission"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('shipment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('carrier_id', models.CharField(max_length=255)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('shipment_status', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(max_length=100)),
                ('estimated_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('failed_shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('packing_list_id', models.CharField(max_length=255)),
                ('shipping_cost_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"distribution"."shipment_details"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('shipping_cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('packing_list_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"distribution"."shipping_cost"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."users"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."vendor"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('stored_materials', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."warehouse"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceAllocation',
            fields=[
                ('allocation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('requesting_dept_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('current_dept_id', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"human_resources"."workforce_allocation"',
                'managed': False,
            },
        ),
    ]
