# Generated by Django 5.1.6 on 2025-03-19 08:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('specific_notes', models.TextField(blank=True, null=True)),
                ('quantity_of_unit', models.IntegerField(default=1)),
                ('cost_per_raw_material', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost_of_raw_materials', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartnerMaster',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('phone', models.TextField(max_length=255)),
                ('job_title', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('goods_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 19, 16, 43, 35, 629937), null=True)),
                ('issue_by', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 43, 35, 629937))),
            ],
        ),
        migrations.CreateModel(
            name='NonProjectOrderPricing',
            fields=[
                ('non_project_costing_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_of_raw_materials', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('effective_date', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 43, 35, 629937))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('unit_of_measure', models.TextField(default='kg', max_length=255)),
                ('stock', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(default='kg')),
            ],
        ),
        migrations.CreateModel(
            name='ReworkOrder',
            fields=[
                ('rework_id', models.AutoField(primary_key=True, serialize=False)),
                ('rework_status', models.TextField()),
                ('rework_date', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 43, 35, 629937))),
                ('expected_completion', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 43, 35, 629937))),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccounts',
            fields=[
                ('gl_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.TextField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.chartofaccounts')),
            ],
        ),
    ]
