# Generated by Django 5.1.6 on 2025-03-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprojectorderpricing',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.policies'),
        ),
        migrations.AddField(
            model_name='nonprojectorderpricing',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_price', to='misc.product'),
        ),
        migrations.AddField(
            model_name='bom',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='misc.product'),
        ),
        migrations.AddField(
            model_name='bom',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.rawmaterials'),
        ),
    ]
