# Generated by Django 5.1.6 on 2025-03-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialReceipts',
            fields=[
                ('or_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('or_date', models.DateField()),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"accounting"."official_receipts"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='chartofaccounts',
            table='"accounting"."chart_of_accounts"',
        ),
    ]
