# Generated by Django 5.1.6 on 2025-03-19 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0015_alter_goodsissue_issue_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_by',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 0, 45, 45, 736163)),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 20, 0, 45, 45, 736163), null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 0, 45, 45, 734156)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 0, 45, 45, 735167)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 0, 45, 45, 735167)),
        ),
    ]
