# Generated by Django 5.1.6 on 2025-03-20 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0016_alter_goodsissue_issue_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_by',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 13, 10, 336876)),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 20, 11, 13, 10, 336876), null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='effective_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 13, 10, 334877)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='expected_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 13, 10, 335877)),
        ),
        migrations.AlterField(
            model_name='reworkorder',
            name='rework_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 13, 10, 335877)),
        ),
    ]
