from django.db import models
from misc.distribution.models import ReworkOrder, GoodsIssue
from django.contrib import admin
from django.db import connection


class OrderAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Order(models.Model):
    class Status(models.TextChoices):
        PENDING = "Pending"
        PROCESSED = "Processed"
        SHIPPED = "Shipped"
        DELIVERED = "Delivered"
        CANCELLED = "Cancelled"

    class Type(models.TextChoices):
        DIRECT = "Direct"
        SCHEDULED = "Scheduled"
        OPEN = "Open"
        D3_SAMPLE = "D3 Sample"

    order_id = models.CharField(primary_key=True, max_length=255, blank=True)
    quotation = models.ForeignKey(
        to="quotation.Quotation", on_delete=models.SET_NULL, null=True, blank=True
    )
    statement = models.ForeignKey(to="statement.Statement", on_delete=models.CASCADE)
    rework = models.ForeignKey(
        to=ReworkOrder, on_delete=models.SET_NULL, blank=True, null=True
    )
    goods_issue = models.ForeignKey(
        to=GoodsIssue, on_delete=models.SET_NULL, null=True, blank=True
    )
    order_date = models.DateTimeField(auto_now_add=True)
    order_status = models.TextField(choices=Status, default=Status.PENDING)
    order_total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    order_type = models.TextField(choices=Type)

    class Meta:
        managed = False
        db_table = '"sales"."orders"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        else:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO sales.orders (order_date, order_status, order_total_amount, order_type, goods_issue_id, quotation_id, rework_id, statement_id)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING order_id;
                """,
                    [
                        self.order_date,
                        self.order_status,
                        self.order_total_amount,
                        self.order_type,
                        self.goods_issue.goods_issue_id if self.goods_issue else None,
                        self.quotation.quotation_id if self.quotation else None,
                        self.rework.rework_id if self.rework else None,
                        self.statement.statement_id,
                    ],
                )
                row = cursor.fetchone()
                if row:
                    self.order_id = row[
                        0
                    ]  # Update the instance with the new statement_id
