from django.db import models
from misc.project_management.models import ExternalProjectRequest
from django.contrib import admin
from django.db import connection


class OrderAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Order(models.Model):
    class Status(models.TextChoices):
        PENDING = "Pending"
        PROCESSED = "Processed"
        SHIPPED = "Shipped"
        DELIVERED = "Delivered"
        CANCELLED = "Cancelled"

    class Type(models.TextChoices):
        NON_PROJECT_BASED = "Non-Project-Based"
        PROJECT_BASED = "Project-Based"
        SERVICE = "Service"

    order_id = models.CharField(primary_key=True, max_length=255, blank=True)
    quotation = models.ForeignKey(
        to="quotation.Quotation", on_delete=models.SET_NULL, null=True, blank=True
    )
    ext_project_request = models.ForeignKey(
        to=ExternalProjectRequest, on_delete=models.SET_NULL, null=True, blank=True
    )
    statement = models.ForeignKey(to="statement.Statement", on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    order_type = models.TextField(choices=Type)

    class Meta:
        managed = False
        db_table = '"sales"."orders"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.order_id:
            self.update()
        else:
            self.insert()
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    INSERT INTO sales.orders (order_date, order_type, quotation_id, statement_id, ext_project_request_id)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING order_id;
                """,
                [
                    self.order_date,
                    self.order_type,
                    self.quotation.quotation_id if self.quotation else None,
                    self.statement.statement_id,
                    (
                        self.ext_project_request.ext_project_request_id
                        if self.ext_project_request
                        else None
                    ),
                ],
            )
            row = cursor.fetchone()
            if row:
                self.order_id = row[0]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    UPDATE sales.orders 
                    SET order_date = %s, order_type = %s, quotation_id = %s, statement_id = %s, ext_project_request_id = %s
                    WHERE order_id = %s;
                """,
                [
                    self.order_date,
                    self.order_type,
                    self.quotation.quotation_id if self.quotation else None,
                    self.statement.statement_id,
                    (
                        self.ext_project_request.ext_project_request_id
                        if self.ext_project_request
                        else None
                    ),
                    self.order_id,
                ],
            )


class OrderView(models.Model):
    order_id = models.CharField(primary_key=True, max_length=255, blank=True)
    quotation = models.ForeignKey(
        to="quotation.Quotation", on_delete=models.SET_NULL, null=True, blank=True
    )
    ext_project_request = models.ForeignKey(
        to=ExternalProjectRequest, on_delete=models.SET_NULL, null=True, blank=True
    )
    statement = models.ForeignKey(to="statement.Statement", on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    order_type = models.TextField()
    completion_status = models.TextField()

    class Meta:
        managed = False
        db_table = '"sales"."order_view"'
