from django.db import models
from order.models import Order
from misc.distribution.models import ShipmentDetails, OperationalCost
from django.contrib import admin
from django.db import connection
from statement.models import *


class ShippingDetailsAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class ShippingDetails(models.Model):
    class Method(models.TextChoices):
        STANDARD = "Standard"
        EXPRESS = "Express"
        OVERNIGHT = "Overnight"
        SAME_DAY = "Same-Day"
        INTERNATIONAL = "International"
        LOCAL = "Local"

    class Status(models.TextChoices):
        PENDING = "Pending"
        SHIPPED = "Shipped"
        DELIVERED = "Delivered"
        RETURNED = "Returned"

    shipping_id = models.CharField(primary_key=True, max_length=255, blank=True)
    statement = models.ForeignKey(to=Statement, on_delete=models.CASCADE)
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, null=True, blank=True)
    operational_cost = models.ForeignKey(
        to=OperationalCost, on_delete=models.CASCADE, null=True, blank=True
    )
    shipment = models.ForeignKey(
        to=ShipmentDetails, on_delete=models.CASCADE, null=True, blank=True
    )
    shipping_method = models.TextField(choices=Method)
    tracking_num = models.CharField(unique=True, max_length=50, blank=True, null=True)
    shipping_date = models.DateTimeField(blank=True, null=True)
    estimated_delivery = models.DateTimeField(blank=True, null=True)
    delivery_status = models.TextField(choices=Status)

    class Meta:
        managed = False
        db_table = '"sales"."shipping_details"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.shipping_id:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            self.update()
        else:
            self.insert()

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO sales.shipping_details (order_id, statement_id, operational_cost_id, shipment_id, shipping_method, tracking_num, shipping_date, estimated_delivery, delivery_status)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING shipping_id;
            """,
                [
                    self.order.order_id if self.order else None,
                    self.statement.statement_id if self.statement else None,
                    (
                        self.operational_cost.operational_cost_id
                        if self.operational_cost
                        else None
                    ),
                    self.shipment.shipment_id if self.shipment else None,
                    self.shipping_method,
                    self.tracking_num,
                    self.shipping_date if self.shipping_date else None,
                    self.estimated_delivery,
                    self.delivery_status,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.shipping_id = row[
                    0
                ]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.shipping_details 
                SET order_id = %s, statement_id = %s, operational_cost_id = %s, shipping_method = %s, tracking_num = %s, shipping_date = %s, estimated_delivery = %s, delivery_status = %s
                WHERE shipping_id = %s;
            """,
                [
                    self.shipment.shipment_id if self.shipment else None,
                    self.statement.statement_id if self.statement else None,
                    self.shipping_method,
                    self.tracking_num,
                    self.shipping_date,
                    self.estimated_delivery,
                    self.delivery_status,
                    self.shipping_id,
                ],
            )
