from django.db import models
from order.models import Order
from misc.distribution.models import ShipmentDetails, GoodsIssue, ReworkOrder
from django.contrib import admin
from django.db import connection
from statement.models import *


class DeliveryNoteAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class DeliveryNote(models.Model):
    class Method(models.TextChoices):
        STANDARD = "Standard"
        EXPRESS = "Express"
        OVERNIGHT = "Overnight"
        SAME_DAY = "Same-Day"
        INTERNATIONAL = "International"
        LOCAL = "Local"

    class Status(models.TextChoices):
        PENDING = "Pending"
        SHIPPED = "Shipped"
        DELIVERED = "Delivered"
        RETURNED = "Returned"

    delivery_note_id = models.CharField(primary_key=True, max_length=255, blank=True)
    statement = models.ForeignKey(
        to=Statement, on_delete=models.CASCADE, blank=True, null=True
    )
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, null=True, blank=True)
    shipment = models.ForeignKey(
        to=ShipmentDetails, on_delete=models.CASCADE, null=True, blank=True
    )
    goods_issue = models.ForeignKey(
        to=GoodsIssue, on_delete=models.SET_NULL, blank=True, null=True
    )
    rework = models.ForeignKey(
        to=ReworkOrder, on_delete=models.SET_NULL, blank=True, null=True
    )
    shipping_method = models.TextField(choices=Method)
    preferred_delivery_date = models.DateField()
    actual_delivery_date = models.DateTimeField(blank=True, null=True)
    tracking_num = models.CharField(max_length=50, blank=True, null=True)
    shipping_date = models.DateTimeField(blank=True, null=True)
    estimated_delivery = models.DateTimeField(blank=True, null=True)
    delivery_status = models.TextField(choices=Status)
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"sales"."delivery_note"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.delivery_note_id:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            self.update()
        else:
            self.insert()

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO sales.delivery_note (order_id, statement_id, shipment_id, shipping_method, tracking_num, shipping_date, estimated_delivery, delivery_status, goods_issue_id, rework_id, preferred_delivery_date)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING delivery_note_id;
            """,
                [
                    self.order.order_id if self.order else None,
                    self.statement.statement_id if self.statement else None,
                    self.shipment.shipment_id if self.shipment else None,
                    self.shipping_method,
                    self.tracking_num,
                    self.shipping_date if self.shipping_date else None,
                    self.estimated_delivery,
                    self.delivery_status,
                    self.goods_issue.goods_issue_id if self.goods_issue else None,
                    self.rework.rework_id if self.rework else None,
                    self.preferred_delivery_date,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.delivery_note_id = row[
                    0
                ]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.delivery_note 
                SET order_id = %s, statement_id = %s, shipping_method = %s, tracking_num = %s, shipping_date = %s, estimated_delivery = %s, delivery_status = %s, goods_issue_id = %s, rework_id = %s, preferred_delivery_date = %s
                WHERE delivery_note_id = %s;
            """,
                [
                    self.shipment.shipment_id if self.shipment else None,
                    self.statement.statement_id if self.statement else None,
                    self.shipping_method,
                    self.tracking_num,
                    self.shipping_date,
                    self.estimated_delivery,
                    self.delivery_status,
                    self.goods_issue.goods_issue_id if self.goods_issue else None,
                    self.rework.rework_id if self.rework else None,
                    self.delivery_note_id,
                    self.preferred_delivery_date,
                ],
            )
