from django.db import models
from datetime import datetime
from order.models import Order
from delivery.models import ShippingDetails
from customer.models import Customer
from django.contrib import admin
from django.db import connection


class Payments(models.Model):
    class Method(models.TextChoices):
        CREDIT_CARD = "Credit Card"
        BANK_TRANSFER = "Bank Transfer"
        CASH = "Cash"

    class Status(models.TextChoices):
        PENDING = "Pending"
        COMPLETED = "Completed"
        FAILED = "Failed"

    payment_id = models.CharField(primary_key=True, max_length=255)
    order = models.ForeignKey(Order, models.CASCADE)
    payment_method = models.TextField(choices=Method)
    payment_status = models.TextField(choices=Status)
    payment_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"sales"."payments"'


class SalesInvoicesAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class SalesInvoices(models.Model):
    class InvoiceStatus(models.TextChoices):
        PENDING = "Pending"
        PAID = "Paid"
        OVERDUE = "Overdue"

    invoice_id = models.CharField(primary_key=True, max_length=255)
    order = models.ForeignKey(
        to="order.Order", on_delete=models.CASCADE, related_name="invoice"
    )
    invoice_date = models.DateTimeField(default=datetime.now())
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    invoice_status = models.TextField(
        choices=InvoiceStatus, default=InvoiceStatus.PENDING
    )
    payment_status = models.TextField(
        choices=Payments.Status, default=Payments.Status.PENDING
    )
    due_date = models.DateField()

    class Meta:
        managed = False
        db_table = '"sales"."sales_invoices"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.invoice_id:
            self.update()
        else:
            self.insert()
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    INSERT INTO sales.sales_invoices (order_id, total_amount, invoice_status, payment_status, due_date)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING invoice_id;
                """,
                [
                    self.order.order_id,
                    self.total_amount,
                    self.invoice_status,
                    self.payment_status,
                    self.due_date,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.invoice_id = row[
                    0
                ]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.sales_invoices 
                SET order_id = %s, total_amount = %s, invoice_status = %s, payment_status = %s, due_date = %s
                WHERE invoice_id = %s
            """,
                [
                    self.order.order_id,
                    self.total_amount,
                    self.invoice_status,
                    self.payment_status,
                    self.due_date,
                    self.invoice_id,
                ],
            )


class Receipt(models.Model):
    receipt_id = models.CharField(primary_key=True, max_length=255, blank=True)
    shipping = models.ForeignKey(ShippingDetails, models.DO_NOTHING)
    customer = models.ForeignKey(Customer, models.CASCADE)
    payments = models.ForeignKey(Payments, models.DO_NOTHING)
    policy_id = models.CharField(max_length=255)
    date_signed = models.DateField(blank=True, null=True)
    signed_docu = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"sales"."receipt"'
