from django.db import models
from datetime import datetime
from order.models import Order
from customer.models import Customer
from django.contrib import admin
from django.db import connection


class Payments(models.Model):
    class Method(models.TextChoices):
        CREDIT_CARD = "Credit Card"
        BANK_TRANSFER = "Bank Transfer"
        CASH = "Cash"

    class Status(models.TextChoices):
        PENDING = "Pending"
        COMPLETED = "Completed"
        FAILED = "Failed"

    payment_id = models.CharField(primary_key=True, max_length=255)
    order = models.ForeignKey(Order, models.CASCADE)
    payment_method = models.TextField(choices=Method)
    payment_status = models.TextField(choices=Status)
    payment_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"sales"."payments"'


class SalesInvoicesAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class SalesInvoices(models.Model):
    invoice_id = models.CharField(primary_key=True, max_length=255)
    delivery_note = models.ForeignKey(
        to="delivery.DeliveryNote", on_delete=models.CASCADE, related_name="invoice"
    )
    invoice_date = models.DateTimeField(default=datetime.now())
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount_paid = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    remaining_balance = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )

    class Meta:
        managed = False
        db_table = '"sales"."sales_invoices"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.invoice_id:
            self.update()
        else:
            self.insert()
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    INSERT INTO sales.sales_invoices (delivery_note_id, total_amount, total_amount_paid)
                    VALUES (%s, %s, %s)
                    RETURNING invoice_id;
                """,
                [
                    self.delivery_note.delivery_id,
                    self.total_amount,
                    self.total_amount_paid,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.invoice_id = row[
                    0
                ]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE sales.sales_invoices 
                SET delivery_note_id = %s, invoice_date = %s, total_amount = %s, total_amount_paid = %s
                WHERE invoice_id = %s
            """,
                [
                    self.delivery_note.delivery_note_id,
                    self.invoice_date,
                    self.total_amount,
                    self.total_amount_paid,
                    self.invoice_id,
                ],
            )


class SalesInvoicesView(models.Model):
    invoice_id = models.CharField(primary_key=True, max_length=255)
    delivery_note = models.ForeignKey(
        to="delivery.DeliveryNote", on_delete=models.CASCADE
    )
    invoice_date = models.DateTimeField(default=datetime.now())
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount_paid = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    remaining_balance = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    payment_status = models.TextField()

    class Meta:
        managed = False
        db_table = '"sales"."sales_invoices_view"'
