# Generated by Django 5.1.6 on 2025-03-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('shipping_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('operational_cost_id', models.CharField(max_length=255)),
                ('shipping_method', models.TextField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('Overnight', 'Overnight'), ('Same-Day', 'Same Day'), ('International', 'International'), ('Local', 'Local')])),
                ('tracking_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.TextField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.shipmentdetails')),
            ],
            options={
                'db_table': '"sales"."shipping_details"',
            },
        ),
    ]
