# Generated by Django 5.1.6 on 2025-03-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
    ]
