from django.db import models
from misc.admin.models import Products
from misc.human_resources.models import Employees
from django.db import connection
from django.contrib import admin
from django.utils import timezone
from misc.project_management.models import ExternalProjectRequest


class StatementAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Statement(models.Model):
    statement_id = models.CharField(primary_key=True, max_length=255, blank=True)
    customer = models.ForeignKey(to="customer.Customer", on_delete=models.CASCADE)
    salesrep = models.ForeignKey(to=Employees, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_tax = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"sales"."statement"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        else:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO sales.statement (customer_id, salesrep_id, total_amount, discount, total_tax)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING statement_id;
                """,
                    [
                        self.customer.customer_id,
                        self.salesrep.employee_id,
                        self.total_amount,
                        self.discount,
                        self.total_tax,
                    ],
                )
                row = cursor.fetchone()
                if row:
                    self.statement_id = row[
                        0
                    ]  # Update the instance with the new statement_id


class StatementItem(models.Model):
    class DemandLevel(models.TextChoices):
        LOW = "Low"
        MEDIUM = "Medium"
        HIGH = "High"
        VERY_HIGH = "Very High"
        SEASONAL = "Seasonal"

    class ReturnAction(models.TextChoices):
        CREDIT = "Credit"
        REPAIR = "Repair"
        REPLACE = "Replace"
        RETURN = "Return"
        DEFINE_NEW = "Define New"

    statement_item_id = models.CharField(primary_key=True, max_length=255, blank=True)
    statement = models.ForeignKey(to=Statement, on_delete=models.CASCADE)
    product = models.ForeignKey(
        to=Products, on_delete=models.SET_NULL, null=True, blank=True
    )
    additional_service_id = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    renewal = models.ForeignKey(
        to="warranty.RenewalWarranty", on_delete=models.SET_NULL, blank=True, null=True
    )
    quantity = models.IntegerField()
    quantity_to_deliver = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    return_reason = models.TextField(blank=True, null=True)
    return_action = models.TextField(choices=ReturnAction, null=True, blank=True)
    quantity_delivered = models.IntegerField(default=0, blank=True)
    created_at = models.DateTimeField(default=timezone.now())

    class Meta:
        managed = False
        db_table = '"sales"."statement_item"'
