from django.db import models, connection
from django.contrib import admin


class BlanketAgreementAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class BlanketAgreement(models.Model):
    class Status(models.TextChoices):
        ACTIVE = "Active"
        EXPIRED = "Expired"
        CANCELLED = "Cancelled"

    class Method(models.TextChoices):
        WRITTEN = "Written"
        ORAL = "Oral"
        ELECTRONIC = "Electronic"

    agreement_id = models.CharField(primary_key=True, max_length=255, blank=True)
    statement = models.ForeignKey(to="statement.Statement", on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    status = models.TextField(choices=Status)
    description = models.TextField(null=True, blank=True)
    signed_date = models.DateTimeField(null=True, blank=True)
    agreement_method = models.TextField(choices=Method)

    class Meta:
        managed = False
        db_table = '"sales"."blanket_agreement"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        elif self.agreement_id:
            self.update()
        else:
            self.insert()
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id

    def insert(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    INSERT INTO sales.blanket_agreement (statement_id, quotation_id, start_date, end_date, status, description, signed_date, agreement_method)                    
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    RETURNING agreement_id;
                """,
                [
                    self.statement.statement_id if self.statement else None,
                    self.start_date,
                    self.end_date,
                    self.status,
                    self.description,
                    self.signed_date,
                    self.agreement_method,
                ],
            )
            row = cursor.fetchone()
            if row:
                self.agreement_id = row[
                    0
                ]  # Update the instance with the new statement_id

    def update(self):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    UPDATE sales.blanket_agreement 
                    SET statement_id = %s , quotation_id= %s, start_date = %s, end_date = %s, status = %s, description = %s, signed_date = %s, agreement_method = %s                    
                    WHERE agreement_id %s;
                """,
                [
                    self.statement.statement_id if self.statement else None,
                    self.start_date,
                    self.end_date,
                    self.status,
                    self.description,
                    self.signed_date,
                    self.agreement_method,
                    self.agreement_id,
                ],
            )
