# Generated by Django 5.1.6 on 2025-03-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlanketAgreement',
            fields=[
                ('agreement_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')])),
                ('description', models.TextField(blank=True, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('agreement_method', models.TextField(choices=[('Written', 'Written'), ('Oral', 'Oral'), ('Electronic', 'Electronic')])),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement')),
            ],
            options={
                'db_table': 'sales.blanket_agreement',
            },
        ),
    ]
