# Generated by Django 5.1.6 on 2025-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlanketAgreement',
            fields=[
                ('agreement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')])),
                ('description', models.TextField(blank=True, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('agreement_method', models.TextField(choices=[('Written', 'Written'), ('Oral', 'Oral'), ('Electronic', 'Electronic')])),
            ],
        ),
    ]
