# Generated by Django 5.1.6 on 2025-03-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blanketagreement',
            options={'managed': False},
        ),
    ]
