# Generated by Django 5.1.6 on 2025-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blanketagreement',
            table='"sales"."blanket_agreement"',
        ),
    ]
