# Generated by Django 5.1.6 on 2025-03-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreement', '0001_initial'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanketagreement',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement'),
        ),
    ]
