from django.db import models, connection
from statement.serializers import *
from datetime import datetime
from django.contrib import admin


class QuotationAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Quotation(models.Model):
    class Status(models.TextChoices):
        PENDING = "Pending"
        APPROVED = "Approved"
        REJECTED = "Rejected"

    quotation_id = models.CharField(primary_key=True, max_length=255, blank=True)
    statement = models.ForeignKey(to="statement.Statement", on_delete=models.CASCADE)
    agreement = models.ForeignKey(
        to="agreement.BlanketAgreement",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    date_issued = models.DateTimeField(auto_now_add=True)
    status = models.TextField(choices=Status, default=Status.PENDING)

    class Meta:
        managed = False
        db_table = '"sales"."quotation"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        else:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO sales.quotation (statement_id, agreement_id, date_issued, status)
                    VALUES (%s, %s, %s, %s)
                    RETURNING quotation_id;
                """,
                    [
                        self.statement.statement_id,
                        self.agreement.agreement_id if self.agreement else None,
                        self.date_issued or datetime.now(),
                        self.status,
                    ],
                )
                row = cursor.fetchone()
                if row:
                    self.quotation_id = row[
                        0
                    ]  # Update the instance with the new statement_id
