# Generated by Django 5.1.6 on 2025-03-20 09:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoices',
            fields=[
                ('invoice_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2025, 3, 20, 17, 55, 1, 787213))),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_status', models.TextField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending')),
                ('payment_status', models.TextField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid')),
                ('due_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='order.order')),
            ],
            options={
                'db_table': 'sales.sales_invoices',
            },
        ),
    ]
