# Generated by Django 5.1.6 on 2025-03-21 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 18, 56, 19, 802060)),
        ),
    ]
