# Generated by Django 5.1.6 on 2025-03-21 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_salesinvoices_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 508623)),
        ),
        migrations.AlterModelTable(
            name='salesinvoices',
            table='"sales"."sales_invoices"',
        ),
    ]
