# Generated by Django 5.1.6 on 2025-03-22 07:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('delivery', '0001_initial'),
        ('invoice', '0004_alter_salesinvoices_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('payment_method', models.TextField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')])),
                ('payment_status', models.TextField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')])),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"sales"."payments"',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 26, 19, 25466)),
        ),
        migrations.AlterField(
            model_name='salesinvoices',
            name='payment_status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('policy_id', models.CharField(max_length=255)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('signed_docu', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('payments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.payments')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.shippingdetails')),
            ],
            options={
                'db_table': '"sales"."receipt"',
            },
        ),
    ]
