# Generated by Django 5.1.6 on 2025-03-21 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_salesinvoices_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 11, 24, 219195)),
        ),
    ]
