# Generated by Django 5.1.6 on 2025-03-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_payments_alter_salesinvoices_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesinvoices',
            options={'managed': False},
        ),
    ]
