# Generated by Django 5.1.6 on 2025-03-19 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_salesinvoices_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 23, 4, 54, 610494)),
        ),
    ]
