# Generated by Django 5.1.6 on 2025-03-21 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_salesinvoices_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 26, 40, 244623)),
        ),
    ]
