# Generated by Django 5.1.6 on 2025-03-20 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_salesinvoices_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoices',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 20, 11, 13, 17, 263719)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 13, 10, 333873)),
        ),
    ]
