# Generated by Django 5.1.6 on 2025-03-20 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_salesinvoices_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 26, 29, 402861)),
        ),
    ]
