# Generated by Django 5.1.6 on 2025-03-21 17:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCosting',
            fields=[
                ('sales_costing_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 645096))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('non_project_costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.nonprojectorderpricing')),
                ('project_resources_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.externalprojectcostmanagement')),
            ],
            options={
                'db_table': '"sales"."sales_costing"',
            },
        ),
    ]
