# Generated by Django 5.1.6 on 2025-03-19 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCosting',
            fields=[
                ('sales_costing_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 43, 35, 598689))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
