# Generated by Django 5.1.6 on 2025-03-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescosting',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.bom'),
        ),
        migrations.AddField(
            model_name='salescosting',
            name='non_project_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.nonprojectorderpricing'),
        ),
    ]
