# Generated by Django 5.1.6 on 2025-03-21 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_alter_salescosting_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescosting',
            old_name='project_resources_id',
            new_name='project_resources',
        ),
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 36, 8, 76509)),
        ),
    ]
