# Generated by Django 5.1.6 on 2025-03-22 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_rename_project_resources_id_salescosting_project_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 26, 19, 20947)),
        ),
    ]
