# Generated by Django 5.1.6 on 2025-03-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_alter_salescosting_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescosting',
            options={'managed': False},
        ),
    ]
