# Generated by Django 5.1.6 on 2025-03-21 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_alter_salescosting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 11, 24, 203552)),
        ),
    ]
