# Generated by Django 5.1.6 on 2025-03-21 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_alter_salescosting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 26, 40, 228572)),
        ),
    ]
