# Generated by Django 5.1.6 on 2025-03-19 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0014_alter_salescosting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescosting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 23, 52, 38, 655363)),
        ),
    ]
