from django.db import models
from misc.accounting.models import GeneralLedgerAccounts
from misc.admin.models import BusinessPartnerMaster
from django.contrib import admin
from django.db import connection

# Create your models here.


class CustomerAdmin(admin.ModelAdmin):
    def save_model(self, request, obj, form, change):
        """Set a flag before saving so that the model knows it's from the admin panel."""
        obj._from_admin = True  # Mark as coming from the admin panel
        obj.save()  # Calls the model's save method


class Customer(models.Model):
    class Type(models.TextChoices):
        LEAD = "Lead"
        PROSPECT = "Prospect"
        CLIENT = "Client"

    class Status(models.TextChoices):
        ACTIVE = "Active"
        INACTIVE = "Inactive"

    customer_id = models.CharField(primary_key=True, max_length=255, blank=True)
    partner = models.ForeignKey(
        to=BusinessPartnerMaster, on_delete=models.SET_NULL, blank=True, null=True
    )
    gl_account = models.ForeignKey(
        to=GeneralLedgerAccounts, on_delete=models.SET_NULL, null=True, blank=True
    )
    name = models.CharField(max_length=255, default="")
    email_address = models.CharField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=20)
    address_line1 = models.TextField(max_length=255)
    address_line2 = models.TextField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)
    customer_type = models.TextField(choices=Type)
    status = models.TextField(choices=Status)
    debt = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        managed = False
        db_table = '"sales"."customers"'

    def save(self, *args, **kwargs):
        if hasattr(self, "_from_admin") and self._from_admin:
            # If coming from admin, use the default Django ORM save
            super().save(*args, **kwargs)
        else:
            # needed because postgres autogenerates id and django
            # cant return the autogenerated id
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                   INSERT INTO sales.customers (gl_account_id, partner_id, name, email_address, phone_number, address_line1, address_line2, city, postal_code, country, customer_type, status, debt)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING quotation_id;
                """,
                    [
                        self.gl_account.gl_account_id if self.gl_account else None,
                        self.partner.partner_id if self.partner else None,
                        self.name,
                        self.email_address,
                        self.phone_number,
                        self.address_line1,
                        self.address_line2,
                        self.city,
                        self.postal_code,
                        self.country,
                        self.customer_type,
                        self.status,
                        self.debt,
                    ],
                )
                row = cursor.fetchone()
                if row:
                    self.quotation_id = row[
                        0
                    ]  # Update the instance with the new statement_id
