from rest_framework import viewsets
from .serializers import *
from django.db import transaction, connection
from rest_framework.response import Response
from rest_framework import status
from rest_framework.request import Request


class CustomerViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

    def list(self, request: Request, *args, **kwargs):
        params = request.query_params
        status = params.get("status")
        type = params.get("type")
        filters = {}
        if status:
            filters["status"] = status
        if type:
            filters["type"] = type

        return Response(
            self.serializer_class(self.queryset.filter(**filters), many=True).data
        )

    def create(self, request, *args, **kwargs):
        """
        inputs:
        {
            name,
            email_address,
            phone_number,
            country,
            city,
            postal_code,
            address_line1,
            address_line2,
            customer_type,
            status (default 'Active'),
            debt (default 0)
        }
        """

        try:
            with transaction.atomic():
                # add customer to business partner masterlist
                partner_id = None
                with connection.cursor() as cursor:
                    # used cursor because db id is autogenerated, causing blank pks when returning model instances
                    cursor.execute(
                        """
                        INSERT INTO admin.business_partner_master(partner_name, category, contact_info)
                        VALUES (%s, %s, %s)
                        RETURNING partner_id; 
                        """,
                        [
                            request.data.get("name"),
                            "Customer",
                            request.data.get("phone_number"),
                        ],
                    )
                    row = cursor.fetchone()
                    if row:
                        partner_id = row[0]

                c_serializer = CustomerSerializer(
                    data={**request.data, "partner": partner_id}
                )
                if c_serializer.is_valid():
                    customer: Customer = c_serializer.save()
                    if partner_id:
                        bp = BusinessPartnerMaster.objects.get(pk=partner_id)
                        bp.customer_id = customer.customer_id
                        bp.save()

                    return Response(
                        CustomerSerializer(customer).data,
                        status=status.HTTP_201_CREATED,
                    )

                else:
                    raise Exception(c_serializer.errors)
        except Exception as error:
            return Response({"error": str(error)}, status=status.HTTP_400_BAD_REQUEST)

        return super().create(request, *args, **kwargs)
