from rest_framework import viewsets
from .serializers import *
from django.db import transaction, connection
from rest_framework.response import Response
from rest_framework import status


class CustomerViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

    def create(self, request, *args, **kwargs):
        """
        inputs:
        {
            name,
            email_address,
            phone_number,
            country,
            city,
            postal_code,
            address_line1,
            address_line2,
            customer_type,
            status (default 'Active'),
            debt (default 0)
        }
        """

        try:
            with transaction.atomic():
                # add customer to business partner masterlist
                partner_id = None

                # used cursor because db id is autogenerated, causing blank items when returning model instances
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                    INSERT INTO admin.business_partner_master(partner_name, category, contact_info)
                    VALUES (%s, %s, %s)
                    RETURNING partner_id; 
                    """,
                        [
                            request.data.get("name"),
                            "Customer",
                            request.data.get("phone_number"),
                        ],
                    )
                    row = cursor.fetchone()
                    if row:
                        partner_id = row[0]

                c_serializer = CustomerSerializer(
                    data={**request.data, "partner": partner_id}
                )
                if c_serializer.is_valid():
                    customer: Customer = c_serializer.save()
                    return Response(
                        CustomerSerializer(customer).data,
                        status=status.HTTP_201_CREATED,
                    )
                else:
                    raise Exception(c_serializer.errors)
        except Exception as error:
            return Response({"error": str(error)}, status=status.HTTP_400_BAD_REQUEST)

        return super().create(request, *args, **kwargs)
