# Generated by Django 5.1.6 on 2025-03-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        ('customer', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_reason', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesrep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StatementItem',
            fields=[
                ('statement_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('demand_level', models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High'), ('Seasonal', 'Seasonal')], default='Low')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_reason', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.product')),
                ('sales_costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.salescosting')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement')),
            ],
        ),
    ]
