# Generated by Django 5.1.6 on 2025-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='type',
            field=models.TextField(choices=[('Project Based', 'Project Based'), ('Non-Project Based', 'Non Project Based'), ('Service', 'Service')], default='Non-Project Based'),
            preserve_default=False,
        ),
    ]
