# Generated by Django 5.1.6 on 2025-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_alter_statement_table_alter_statementitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.TextField(choices=[('Project Based', 'Project Based'), ('Non-Project-Based', 'Non Project Based'), ('Service', 'Service')]),
        ),
    ]
