# Generated by Django 5.1.6 on 2025-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_statement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='statementitem',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
