# Generated by Django 5.1.6 on 2025-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_alter_statementitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
