# Generated by Django 5.1.6 on 2025-03-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_alter_statement_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementitem',
            name='discount_reason',
        ),
    ]
