# Generated by Django 5.1.6 on 2025-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0005_remove_statementitem_discount_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
