# Generated by Django 5.1.6 on 2025-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_statementitem_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
