# Generated by Django 5.1.6 on 2025-03-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '__first__'),
        ('quotation', '0001_initial'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.TextField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending')),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.TextField(choices=[('Direct', 'Direct'), ('Scheduled', 'Scheduled'), ('Open', 'Open'), ('D3 Sample', 'D3 Sample')])),
                ('goods_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.goodsissue')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.quotation')),
                ('rework_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.reworkorder')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statement')),
            ],
            options={
                'db_table': 'sales.orders',
            },
        ),
    ]
