# Generated by Django 5.1.6 on 2025-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='"sales"."orders"',
        ),
    ]
