# Generated by Django 5.1.6 on 2025-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.TextField(choices=[('Direct', 'Direct'), ('Scheduled', 'Scheduled'), ('Open', 'Open'), ('D3 Sample', 'D3 Sample')], default='Direct'),
            preserve_default=False,
        ),
    ]
