# Generated by Django 5.1.6 on 2025-03-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_type'),
        ('quotation', '0003_remove_quotation_is_cancelled_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quotation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.quotation'),
        ),
    ]
