# Generated by Django 5.1.6 on 2025-03-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_quotation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quotation_id',
            new_name='quotation',
        ),
    ]
