# Generated by Django 5.1.6 on 2025-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_quotation_id_order_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
