# Generated by Django 5.1.6 on 2025-03-21 17:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('type', models.TextField(choices=[('Email', 'Email'), ('Social Media', 'Social Media'), ('Referral', 'Referral'), ('Advertisement', 'Advertisement')], default='Email')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 653114))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 653114))),
                ('status', models.TextField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed')], default='Active')),
            ],
            options={
                'db_table': '"sales"."campaigns"',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lead_name', models.CharField(max_length=255)),
                ('lead_email', models.CharField(max_length=255)),
                ('lead_phonenum', models.CharField(max_length=20)),
                ('source', models.TextField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Email', 'Email')], default='Website')),
                ('status', models.TextField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New')),
                ('salesrep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employees')),
            ],
            options={
                'db_table': '"sales"."leads"',
            },
        ),
        migrations.CreateModel(
            name='CampaignContacts',
            fields=[
                ('contact_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('response_status', models.TextField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Pending', 'Pending')], default='Pending')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='CRM.campaigns')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='CRM.leads')),
            ],
            options={
                'db_table': '"sales"."campaign_contacts"',
            },
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('opportunity_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_closed_date', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 654111))),
                ('stage', models.TextField(choices=[('Prospecting', 'Prospecting'), ('Negotiation', 'Negotiation'), ('Closed', 'Closed')])),
                ('status', models.TextField(choices=[('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')])),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_lost', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 654111))),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.businesspartnermaster')),
                ('salesrep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.employees')),
            ],
            options={
                'db_table': '"sales"."opportunities"',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.TextField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')])),
                ('priority', models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 655250))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesrep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.employees')),
            ],
            options={
                'db_table': '"sales"."ticket"',
            },
        ),
        migrations.CreateModel(
            name='TicketConvo',
            fields=[
                ('convo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 1, 26, 47, 655250))),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='CRM.ticket')),
            ],
            options={
                'db_table': '"sales"."ticket_convo"',
            },
        ),
    ]
