# Generated by Django 5.1.6 on 2025-03-19 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 50, 19, 812631)),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 50, 19, 812631)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 50, 19, 812631)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='expected_closed_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 50, 19, 812631)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 50, 19, 812631)),
        ),
        migrations.AlterField(
            model_name='ticketconvo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 50, 19, 812631)),
        ),
    ]
