# Generated by Django 5.1.6 on 2025-03-21 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_campaigns_end_date_alter_campaigns_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 493012)),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 493012)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 493012)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='expected_closed_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 493012)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 493012)),
        ),
        migrations.AlterField(
            model_name='ticketconvo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 23, 10, 30, 493012)),
        ),
        migrations.AlterModelTable(
            name='campaigncontacts',
            table='"sales"."campaign_contacts"',
        ),
        migrations.AlterModelTable(
            name='opportunities',
            table='"sales"."opportunities"',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='"sales"."ticket"',
        ),
        migrations.AlterModelTable(
            name='ticketconvo',
            table='"sales"."ticket_convo"',
        ),
    ]
