# Generated by Django 5.1.6 on 2025-03-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_alter_campaigns_end_date_alter_campaigns_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigncontacts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='campaigns',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leads',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='opportunities',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ticketconvo',
            options={'managed': False},
        ),
    ]
