# Generated by Django 5.1.6 on 2025-03-19 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_campaigns_end_date_alter_campaigns_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 39, 12, 494697)),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 39, 12, 494697)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 39, 12, 495697)),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='expected_closed_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 39, 12, 495697)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 39, 12, 496698)),
        ),
        migrations.AlterField(
            model_name='ticketconvo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 39, 12, 496698)),
        ),
    ]
